#!/usr/bin/env php
<?php

$selfName = array_shift($argv);

function show_help()
{
	global $selfName;
exit("
Usage: 
	{$selfName} command [parameters]

Available commands:

c[reate]
	page name [alias] [path] [components..]       # Create a bitrix php page
	tpl name [alias] [description] [components..] # Create a template using components
	ibl name iblock_type [code]                   # Create a iblock
	cmp name [alias] [description]	              # Create a component
	cmpin template_name name                      # Create a component's template copy for the site template
	mod name [alias] [description]	              # Create a module

r[emove]
	page name [path]
	tpl name
	ibl id [name] [code]
	cmp name
	cmpin template_name name
	mod name

cl[ear]
	iblock id [name] [code]

i[mport]
	products
		magento hostname apiuser apikey category_id iblock_id
		xls filename iblock_id
");
}

function set_php_settings()
{
	ini_set('display_errors', 1);
	set_time_limit(0);
	date_default_timezone_set("Europe/Moscow");
}

function bitrix_include_modules($modules=array())
{
	if (is_string($modules))
	{
		$modules = preg_replace("#\s+#", "", $modules);
		$modules = explode(",", $modules);
	}

	foreach ($modules as $module)
	{
		if (!CModule::IncludeModule($module))
			diec("Error", "Module {$module} not found");
	}
}

function transliterate($text) 
{
	static $smap, $chars, $regex, $maps;

	if (!isset($maps))
	{
		$maps = array (
			'latin_map' => array (
				'À' => 'A', 'Á' => 'A', 'Â' => 'A', 'Ã' => 'A', 'Ä' => 'A', 'Å' => 'A', 'Æ' => 'AE', 'Ç' =>
				'C', 'È' => 'E', 'É' => 'E', 'Ê' => 'E', 'Ë' => 'E', 'Ì' => 'I', 'Í' => 'I', 'Î' => 'I',
				'Ï' => 'I', 'Ð' => 'D', 'Ñ' => 'N', 'Ò' => 'O', 'Ó' => 'O', 'Ô' => 'O', 'Õ' => 'O', 'Ö' =>
				'O', 'Ő' => 'O', 'Ø' => 'O', 'Ù' => 'U', 'Ú' => 'U', 'Û' => 'U', 'Ü' => 'U', 'Ű' => 'U',
				'Ý' => 'Y', 'Þ' => 'TH', 'ß' => 'ss', 'à' => 'a', 'á' => 'a', 'â' => 'a', 'ã' => 'a', 'ä' =>
				'a', 'å' => 'a', 'æ' => 'ae', 'ç' => 'c', 'è' => 'e', 'é' => 'e', 'ê' => 'e', 'ë' => 'e',
				'ì' => 'i', 'í' => 'i', 'î' => 'i', 'ï' => 'i', 'ð' => 'd', 'ñ' => 'n', 'ò' => 'o', 'ó' =>
				'o', 'ô' => 'o', 'õ' => 'o', 'ö' => 'o', 'ő' => 'o', 'ø' => 'o', 'ù' => 'u', 'ú' => 'u',
				'û' => 'u', 'ü' => 'u', 'ű' => 'u', 'ý' => 'y', 'þ' => 'th', 'ÿ' => 'y'
			),
			'latin_symbols_map' => array (
				'©' => '(c)'
			),
			'greek_map' => array (
				'α' => 'a', 'β' => 'b', 'γ' => 'g', 'δ' => 'd', 'ε' => 'e', 'ζ' => 'z', 'η' => 'h', 'θ' => '8',
				'ι' => 'i', 'κ' => 'k', 'λ' => 'l', 'μ' => 'm', 'ν' => 'n', 'ξ' => '3', 'ο' => 'o', 'π' => 'p',
				'ρ' => 'r', 'σ' => 's', 'τ' => 't', 'υ' => 'y', 'φ' => 'f', 'χ' => 'x', 'ψ' => 'ps', 'ω' => 'w',
				'ά' => 'a', 'έ' => 'e', 'ί' => 'i', 'ό' => 'o', 'ύ' => 'y', 'ή' => 'h', 'ώ' => 'w', 'ς' => 's',
				'ϊ' => 'i', 'ΰ' => 'y', 'ϋ' => 'y', 'ΐ' => 'i',
				'Α' => 'A', 'Β' => 'B', 'Γ' => 'G', 'Δ' => 'D', 'Ε' => 'E', 'Ζ' => 'Z', 'Η' => 'H', 'Θ' => '8',
				'Ι' => 'I', 'Κ' => 'K', 'Λ' => 'L', 'Μ' => 'M', 'Ν' => 'N', 'Ξ' => '3', 'Ο' => 'O', 'Π' => 'P',
				'Ρ' => 'R', 'Σ' => 'S', 'Τ' => 'T', 'Υ' => 'Y', 'Φ' => 'F', 'Χ' => 'X', 'Ψ' => 'PS', 'Ω' => 'W',
				'Ά' => 'A', 'Έ' => 'E', 'Ί' => 'I', 'Ό' => 'O', 'Ύ' => 'Y', 'Ή' => 'H', 'Ώ' => 'W', 'Ϊ' => 'I',
				'Ϋ' => 'Y'
			),
			'turkish_map' => array (
				'ş' => 's', 'Ş' => 'S', 'ı' => 'i', 'İ' => 'I', 'ç' => 'c', 'Ç' => 'C', 'ü' => 'u', 'Ü' => 'U',
				'ö' => 'o', 'Ö' => 'O', 'ğ' => 'g', 'Ğ' => 'G'
			),
			'russian_map' => array (
				'а' => 'a', 'б' => 'b', 'в' => 'v', 'г' => 'g', 'д' => 'd', 'е' => 'e', 'ё' => 'yo', 'ж' => 'zh',
				'з' => 'z', 'и' => 'i', 'й' => 'j', 'к' => 'k', 'л' => 'l', 'м' => 'm', 'н' => 'n', 'о' => 'o',
				'п' => 'p', 'р' => 'r', 'с' => 's', 'т' => 't', 'у' => 'u', 'ф' => 'f', 'х' => 'h', 'ц' => 'c',
				'ч' => 'ch', 'ш' => 'sh', 'щ' => 'sh', 'ъ' => '', 'ы' => 'y', 'ь' => '', 'э' => 'e', 'ю' => 'yu',
				'я' => 'ya',
				'А' => 'A', 'Б' => 'B', 'В' => 'V', 'Г' => 'G', 'Д' => 'D', 'Е' => 'E', 'Ё' => 'Yo', 'Ж' => 'Zh',
				'З' => 'Z', 'И' => 'I', 'Й' => 'J', 'К' => 'K', 'Л' => 'L', 'М' => 'M', 'Н' => 'N', 'О' => 'O',
				'П' => 'P', 'Р' => 'R', 'С' => 'S', 'Т' => 'T', 'У' => 'U', 'Ф' => 'F', 'Х' => 'H', 'Ц' => 'C',
				'Ч' => 'Ch', 'Ш' => 'Sh', 'Щ' => 'Sh', 'Ъ' => '', 'Ы' => 'Y', 'Ь' => '', 'Э' => 'E', 'Ю' => 'Yu',
				'Я' => 'Ya'
			),
			'ukrainian_map' => array (
				'Є' => 'Ye', 'І' => 'I', 'Ї' => 'Yi', 'Ґ' => 'G', 'є' => 'ye', 'і' => 'i', 'ї' => 'yi', 'ґ' => 'g'
			),
			'czech_map' => array (
				'č' => 'c', 'ď' => 'd', 'ě' => 'e', 'ň' => 'n', 'ř' => 'r', 'š' => 's', 'ť' => 't', 'ů' => 'u',
				'ž' => 'z', 'Č' => 'C', 'Ď' => 'D', 'Ě' => 'E', 'Ň' => 'N', 'Ř' => 'R', 'Š' => 'S', 'Ť' => 'T',
				'Ů' => 'U', 'Ž' => 'Z'
			),
			'polish_map' => array (
				'ą' => 'a', 'ć' => 'c', 'ę' => 'e', 'ł' => 'l', 'ń' => 'n', 'ó' => 'o', 'ś' => 's', 'ź' => 'z',
				'ż' => 'z', 'Ą' => 'A', 'Ć' => 'C', 'Ę' => 'e', 'Ł' => 'L', 'Ń' => 'N', 'Ó' => 'O', 'Ś' => 'S',
				'Ź' => 'Z', 'Ż' => 'Z'
			),
			'latvian_map' => array (
				'ā' => 'a', 'č' => 'c', 'ē' => 'e', 'ģ' => 'g', 'ī' => 'i', 'ķ' => 'k', 'ļ' => 'l', 'ņ' => 'n',
				'š' => 's', 'ū' => 'u', 'ž' => 'z', 'Ā' => 'A', 'Č' => 'C', 'Ē' => 'E', 'Ģ' => 'G', 'Ī' => 'i',
				'Ķ' => 'k', 'Ļ' => 'L', 'Ņ' => 'N', 'Š' => 'S', 'Ū' => 'u', 'Ž' => 'Z'
			),
			'special_chars' => array (
				' ' => '_', '+' => '', '"' => '', '\'' => '', ':' => '', ';' => '', '\\' => '', '|' => '', 
				'/' => ''
			)
		);

		foreach ($maps as $map) 
		{
			foreach ($map as $orig => $conv) 
			{
				$smap[$orig] = $conv;
				$chars .= $orig;
			}
		}
	}

	for ($i = 0; $i < strlen($chars); $i++) 
	{
		$char = substr($chars, $i, 1, 'UTF-8');
		$text = str_replace($char, @$smap[$char], $text);
	}

	return $text;
}

function getarg($default=null)
{
	global $argv;

	if (!isset($argv[0]))
	{
		if (is_null($default)) 
			show_help();
		else
			return $default;
	}

	$result = array_shift($argv);

	if ($result=="-") 
	{
		return $default;
	}

	return $result;
}

function diec($action, $comment)
{
	die("\033[1;31m{$action}\033[0m {$comment}\n");
}

function logc($action, $comment)
{
	echo("\033[1;32m{$action}\033[0m {$comment}\n");
}

function warnc($action, $comment)
{
	echo("\033[1;33m{$action}\033[0m {$comment}\n");
}

function get($url, $path)
{
	logc("Download", "getting '$url'");
	if (is_file($path))
		unlink($path);

	if ($rf = fopen($url, "rb")) 
	{
		$lf = fopen($path, "wb");

		if ($lf)
		{
			while (!feof($rf)) 
				fwrite($lf, fread($rf, 1024 * 8 ), 1024 * 8 );
			fclose($lf);
		}

		fclose($rf);
	}
}

function putf($file, $data)
{
	if (@file_put_contents($file, $data)) 
		logc("Create file", $file);
}

function mkd($path)
{
	if (@mkdir($path, 0755)) 
		logc("Create directory", $path);
}

function rm_rf($dir)
{
    foreach (glob($dir.'/*') as $file) 
    {
        if (is_dir($file))
            rm_rf($file);
        else if (@unlink($file)) 
        	logc("Remove file",$file);
    }
    if (@rmdir($dir)) logc("Remove directory", $dir);
}

function cp_r($source, $destination, $rewrite=false)
{
	if (is_file($destination) && $rewrite)
		@unlink($destination);
	if (is_dir($source))
	{
		mkd($destination);
		foreach (glob($source.'/*') as $file)
		{
			if ($file != "." && $file != "..")
				cp_r("$source/$file", "$destination/$file"); 
		}
	}
	else
		if (is_file($source))
			cp($source, $destination);
}

function cp($source, $destination)
{
	if (@copy($source, $destination)) 
		logc("Copy", "from {$source} to {$destination}");
}

function get_components($arr)
{
	$result = "";
	foreach ($arr as $component)
	{
$COMPANENT_TPL = <<<EOF
<?php \$APPLICATION->IncludeComponent(
	"{$component}", 
	".default", 
	array
	(
	
	),
	false
);?>
EOF;
		$result .= $COMPANENT_TPL;
	}
	return $result;
}


$_SERVER["DOCUMENT_ROOT"] = dirname(__FILE__);
$_SERVER["SCRIPT_NAME"]   = "/bx";
$_SERVER["REQUEST_URI"]   = "/bx";
$_SERVER["DOCUMENT_URI"]  = "/bx";
$_SERVER["SCRIPT_URL"]    = "/bx";
$_SERVER["SCRIPT_URI"]    = "/bx";
$DOCUMENT_ROOT            = $_SERVER["DOCUMENT_ROOT"];

define("BITRIX_PROLOG", $_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");

define("LANG", "ru"); 
define("STOP_STATISTICS", true);
define("NO_KEEP_STATISTIC", true);
define("NOT_CHECK_PERMISSIONS", true);

set_php_settings();


$command = getarg();

switch ($command)
{
	case "c":
	case "create":
		$param = getarg();

		switch ($param)
		{
			case "page":
				$name       = getarg();
				$alias      = getarg(transliterate($name));
				$path       = getarg("./");
				$components = get_components($argv);
				$path       = rtrim($path, "/")."/$alias";
$PAGE_TPL = <<<EOF
<?php require(\$_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php"); \$APPLICATION->SetTitle("{$name}"); ?>
{$components}
<?php require(\$_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php"); ?>
EOF;
$SECTION_TPL = <<<EOF
<?php \$sSectionName = "{$name}"; \$arDirProperties = array( ); ?>
EOF;
				mkd($path);
				putf("$path/index.php", $PAGE_TPL);
				putf("$path/.section.php", $SECTION_TPL);
			break;	

			case "tpl":
			case "template":
				$name        = getarg();
				$alias       = getarg(transliterate($name));
				$description = getarg("");
				$components  = get_components($argv);
				$path  = "./bitrix/templates/$alias";
$STYLES_TPL = <<<EOF
<?php \$arStyles = array( ); return \$arStyles; ?>
EOF;
$DESCRIPTION_TPL = <<<EOF
<?php \$arTemplate = Array("NAME"=>"{$name}", "DESCRIPTION"=>"{$description}");?>
EOF;
$HEADER_TPL = <<<EOF
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<?php \$APPLICATION->ShowHead();?>
		<meta name="viewport" content="width=1024; initial-scale=1.0" />

		<title><?php \$APPLICATION->ShowTitle()?></title>

		<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />

		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>

	<body>
		<div id="panel"><?php \$APPLICATION->ShowPanel();?></div>

		<header>
		</header>
		<section>
EOF;
$FOOTER_TPL = <<<EOF
		</section>
		<footer>
		</footer>
	</body>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
	<script src="<?=SITE_TEMPLATE_PATH?>/js/core.js"></script>
</html>
EOF;
$STYLES_TPL = <<<EOF
EOF;
$TEMPLATE_STYLES_TPL = <<<EOF
@import url("css/core.css");
EOF;
$CORE_SCSS_TPL = <<<EOF
@charset "UTF-8";

header {

}

section {

}

footer {

}
EOF;
$CORE_COFFEE_TPL = <<<EOF
(($) ->
	$(document)
		.ready ()->

)(jQuery)
EOF;
				mkd($path);
				mkd("$path/coffee");
				mkd("$path/js");
				mkd("$path/scss");
				mkd("$path/css");
				mkd("$path/images");
				putf("$path/.styles.php", $STYLES_TPL);
				putf("$path/description.php", $DESCRIPTION_TPL);
				putf("$path/header.php", $HEADER_TPL);
				putf("$path/footer.php", $FOOTER_TPL);
				putf("$path/styles.css", $STYLES_TPL);
				putf("$path/template_styles.css", $TEMPLATE_STYLES_TPL);
				putf("$path/scss/core.scss", $CORE_SCSS_TPL);
				putf("$path/coffee/core.coffee", $CORE_COFFEE_TPL);
			break;

			case "ibl":
			case "iblock":
				$name        = getarg();
				$type        = getarg();
				$code        = getarg(transliterate($name));
				$site_id     = getarg("s1");
				$description = getarg("");
				$active      = getarg("Y");
				$sort        = getarg("1");

				require_once(BITRIX_PROLOG);
				set_php_settings();
				bitrix_include_modules("iblock");

				$iblock = new CIBlock();
				$id = $iblock->Add
				(array(
					"ACTIVE"           => $active,
					"NAME"             => $name,
					"CODE"             => $code,
					"LIST_PAGE_URL"    => "#SITE_DIR#/$type/index.php?ID=#IBLOCK_ID#",
					"DETAIL_PAGE_URL"  => "#SITE_DIR#/$type/detail.php?ID=#ID#",
					"SECTION_PAGE_URL" => "#SITE_DIR#/$type/list.php?SECTION_ID=#ID#",
					"IBLOCK_TYPE_ID"   => $type,
					"SITE_ID"          => array($site_id),
					"SORT"             => $sort,
					"PICTURE"          => array(),
					"DESCRIPTION"      => $description,
					"DESCRIPTION_TYPE" => "text",
					"GROUP_ID"         => array("2"=>"R")		
				));
				if ($id) logc("Create iblock", "with id $id");
			break;
		}
	break;

	case "r":
	case "remove":
		$param = getarg();

		switch ($param)
		{
			case "page":
				$name  = getarg();
				$path  = getarg("./");
				$path1 = rtrim($path, "/")."/".transliterate($name);				
				$path2 = rtrim($path, "/")."/".$name;	
				rm_rf($path1);
				rm_rf($path2);
			break;

			case "tpl":
			case "template":
				$name  = getarg();
				$alias = transliterate($name);
				$path  = "./bitrix/templates/$alias";
				rm_rf($path);
			break;

			case "ibl":
			case "iblock":
				$filter = array();
				if ($v = getarg(false)) $filter["ID"]   = $v;
				if ($v = getarg(false)) $filter["NAME"] = $v;
				if ($v = getarg(false)) $filter["CODE"] = $v;

				require_once(BITRIX_PROLOG);
				set_php_settings();
				bitrix_include_modules("iblock");

				$iblocks = CIBlock::GetList
				(
					array("SORT"=>"ASC"),
 					$filter,
 					false
				);

				while ($iblock = $iblocks->Fetch())
				{
					$id = $iblock["ID"];
					$DB->StartTransaction();
					if (!CIBlock::Delete($id))
					{
						$DB->Rollback();
						diec("Error", "Can't remove iblock");
					}
					else
					{
						$DB->Commit();
						logc("Remove iblock", "with id $id");
					}
				}
			break;
		}
	break;

	case "cl":
	case "clear":
		$param = getarg();

		switch ($param)
		{
			case "ibl":
			case "iblock":

			break;
		}
	break;

	case "i":
	case "import":
		$param = getarg();

		switch ($param)
		{
			case "products":
				$param = getarg();

				switch ($param)
				{
					case "magento":
						$host       = getarg();
						$apiuser    = getarg();
						$apikey     = getarg();
						$categoryID = getarg();
						$iblockID   = getarg();

						require_once(BITRIX_PROLOG);
						set_php_settings();
						bitrix_include_modules("iblock");

						$client = new SoapClient("http://{$host}/api/v2_soap/?wsdl");

						$session = $client->login($apiuser, $apikey);

						$categories = $client->catalogCategoryTree($session, $categoryID);
						$products = $client->catalogProductList($session);

						print_r($categories);

						$client->endSession($session);
					break;

					case "xls":
						
					break;
				}
			break;
		}
	break;

	default:
	case "help":
		show_help();
	break;
}

echo "\n";
